services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    networks:
      - recipe-network

  # Auth Service
  auth-service:
    build: ./recipe-auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=admin1
      - DB_NAME=recipe_service_db
      - JWT_SECRET=secret
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks:
      - recipe-network

  # Content Service
  content-service:
    build: ./recipe-content-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=admin1
      - DB_NAME=recipe_service_db
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks:
      - recipe-network

  # Interaction Service
  interaction-service:
    build: ./recipe-interaction-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=admin1
      - DB_NAME=recipe_service_db
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks:
      - recipe-network

  # Gateway
  gateway:
    build: ./recipe-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=secret
      - AUTH_SERVICE_URL=http://auth-service:3001
      - CONTENT_SERVICE_URL=http://content-service:3002
      - INTERACTION_SERVICE_URL=http://interaction-service:3003
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=admin1
      - DB_NAME=recipe_service_db
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      - auth-service
      - content-service
      - interaction-service
    networks:
      - recipe-network

networks:
  recipe-network:
    driver: bridge
