name: Deploy to Yandex VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy repository to server (scp)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: ${{ secrets.REMOTE_PATH }}

      - name: Run remote deploy commands (docker compose)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd ${{ secrets.REMOTE_PATH }}
            # если на VM используются старые файлы, рекомендуем очистить зависимые контейнеры
            docker compose down || docker-compose down || true
            # собрать и поднять
            docker compose pull || true
            docker compose up -d --build --remove-orphans
            # посмотреть, какие контейнеры запущены
            docker compose ps || docker ps -a
